apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
data: #if want to store sensitive data in plain text then put data under -> stringData:
  MONGODB_USER: 'YWRtaW4='   # echo -n "admin" | base64
  MONGODB_PASSWORD: 'cGFzc3dvcmQxMjM=' # echo -n "password123" | base64. K8S is going to decode it back. 