apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1 ## ensure that we do not have more than 3 pod replicas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
      - name: grade-submission-api
        image: rslim087/kubernetes-course-grade-submission-api:stateless
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15 #initial delay, giving the application time to start up before we start probing its endpoint.
          periodSeconds: 5 #after the initial delay, keep probing this endpoint every 5 seconds
        readinessProbe: #sends traffic only if probe is healthy.
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 10 #wait for 10 secs before checking the rediness endpoint. the initial delay is less critical. An unresponsive app during startup correctly indicates it's not yet ready for traffic
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
        ports:
          - containerPort: 3000
