apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  serviceName: mongodb    ## mongodb-0 mongodb-1. Is the prefix that will be used to name every single pod in the stateful set.
  replicas: 1  #keep only one STS else data will be written in two diff PV's.
  template: #skeleton for each pod
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password123"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates: #skeleton for each PVC. One PVC PER stateful pod.
  - metadata:
      name: mongodb-persistent-storage #mongodb-persistent-storage-mongodb-0, mongodb-persistent-storage-mongodb-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi