apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal # 1-1 mapping with container 
  labels:
    app.kubernetes.io/name: grade-submission #Cloud native app
    app.kubernetes.io/component: frontend #Role
    app.kubernetes.io/instance: grade-submission-portal #application 
spec:
  containers:
  - name: grade-submission-portal
    image: rslim087/kubernetes-course-grade-submission-portal
    resources:
      requests:
        memory: "128Mi" #incompressible
        cpu: "200m" #compressible
      limits:
        memory: "128Mi" #Memory can not be throttled but CPU can be, by Kernel scheduler. Memory is incompressible, thus specify a limit for it and not CPU.
    ports:
      - containerPort: 5001  
  - name: grade-submission-portal-health-checker
    image: rslim087/kubernetes-course-grade-submission-portal-health-checker
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"