apiVersion: v1
kind: Secret
metadata:
  name: grade-sa-token
  namespace: grade-demo
  annotations:
    kubernetes.io/service-account.name: grade-sa #associate this secret with the service account
type: kubernetes.io/service-account-token #This secret will be used to extract a token out of the grade service account.
